### ISSUE TITLE
How can i contact you? I need help setting up the bot

### ISSUE THREAD

**Issue by SeasonPhan** [localthomas/discord-rsvp#2]

**Comment by localthomas** [comment]
This is the right place. Just ask your questions.
But keep in mind to not share any of the private values for the Discord application (i.e. the public key, the client-id and client-secret) or replace them with placeholder values.

**Comment by SeasonPhan** [comment]
i cant setup interaction endpoint url
"validation error: The specified interactions endpoint url could not be verified."

after i authorize the bot http://gg.gg/vrd7e
i got redirected to this link https://<my-ip>/<webhook-token>?code=xxxxxxxxxxx&state=xxxxxxxxxxxx&guild_id=xxxxxxxxxxx
then all i got is this message from browser "ERR_CONNECTION_REFUSED"

is this caused by docker?

**Comment by localthomas** [comment]
> i cant setup interaction endpoint url
"validation error: The specified interactions endpoint url could not be verified."

Was the docker container running when you entered the URL? If I remember correctly, discord-rsvp should be running when entering the URL.

**Comment by SeasonPhan** [comment]
yes it was "listening on port 80"

> discord-rsvp should be running when entering the URL.

i have tried to do that first but it didnt work, still the same error
the bot doesnt respone to anything

i have checked all the ports and they works fine.
Do i need to specify the 8080 port in discord interaction url?

**Comment by localthomas** [comment]
> yes it was "listening on port 80"

Well, you need to listen on port 443 with a HTTPS proxy, as discord only supports HTTPS connections.

HTTPS proxies are out of scope for this project, so I can only refer to external tutorials (just search for `docker HTTPS proxy`, you'll find plenty). A proxy with good docker suport might be [traefik](https://doc.traefik.io/traefik/) or maybe [nginx-proxy](https://hub.docker.com/r/jwilder/nginx-proxy) with [SSL support](https://github.com/nginx-proxy/nginx-proxy#ssl-support-using-an-acme-ca).

You can check the HTTPS-setup by visiting your interaction URL in a browser and either receive a blank page without errors (Firefox) or a HTTP Error 401 error page (Chrome).

**Comment by SeasonPhan** [comment]
Should i keep starting the container with -p 8080:80  ?

So the final setup should be something like

Docker port 80 -> port 8080 -> Proxy to port 443?

**Comment by localthomas** [comment]
That depends on the HTTPS proxy. Either it connects via an external port (e.g. `-p 8080:80`) or just uses the internally exposed port 80 (e.g. with [letsencrypt-nginx-proxy-companion](https://hub.docker.com/r/jrcs/letsencrypt-nginx-proxy-companion/)).

**Comment by SeasonPhan** [comment]
> You can check the HTTPS-setup by visiting your interaction URL in a browser and either receive a blank page without errors (Firefox) or a HTTP Error 401 error page (Chrome).

im getting 401 error page, am i doing it right?

the container can receive request from discord now but the logs write 
'http: panic serving my-public-ip:43158: ed25519: bad public key length: 64...."

**Comment by localthomas** [comment]
> im getting 401 error page, am i doing it right?

Yes. If you are getting this page, it should mean that your successfully had contact with the discord-rsvp container.

> the container can receive request from discord now but the logs write
'http: panic serving my-public-ip:43158: ed25519: bad public key length: 64...."

I think you did not provide the field `HexEncodedDiscordPublicKey` in the config.json or the value is invalid/malformed.

**Comment by SeasonPhan** [comment]
> I think you did not provide the field `HexEncodedDiscordPublicKey` in the config.json or the value is invalid/malformed.

what tool did u use to convert?, im just using an online converter and the problem doesnt goes away

**Comment by localthomas** [comment]
No tool. Just go to the discord [applications](https://discord.com/developers/applications), select the application, go to *General Information* and click the button `Copy` under the *Public Key* field.

**Comment by SeasonPhan** [comment]
i have successfully added interaction endpoint url ( i use a domain point to my ip address), but


> after i authorize the bot http://gg.gg/vrd7e
> i got redirected to this link https:///?code=xxxxxxxxxxx&state=xxxxxxxxxxxx&guild_id=xxxxxxxxxxx
> then all i got is this message from browser "ERR_CONNECTION_REFUSED"


now it says HTTP ERROR 401

**Comment by localthomas** [comment]
> now it says HTTP ERROR 401

That might not actually be a problem, but the redirection URL seems broken.
Did you add a redirect in the format `https://example.org/webhook-token` to the OAuth2 page of the application?
I.e. go to the discord [applications](https://discord.com/developers/applications), select the application, go to *OAuth2* and *Redirects* add one.

**Comment by SeasonPhan** [comment]
oh so i have to put literally https://domain/WEBHOOK-TOKEN
i now have everything figured out and the bot works perfect now, thanks xd
